segon_bat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('temes.urls')),
]

temes/urls.py
from django.urls import path
from temes import views

app_name = 'temes'

urlpatterns = [
    path('', views.temes, name='temes'),
    path('exercicis/<int:id>', views.exercicis, name='exercicis'),
    path("exercicis/exercici_numero=<int:pk>", views.show_exercici, name='show')
]

temes/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=225, unique=True, default="")
    link_teoria = models.CharField(max_length=225, null=True)
    # slug = models.SlugField(blank=True, default='')

    def __str__(self):
        return self.title
    #
    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title)
    #     super(Category, self).save()
    #
    # def get_absolute_url(self):  # < here
    #     return reverse('detail', args=[str(self.slug)])

class Exercici(models.Model):
    exercici = models.IntegerField()
    any = models.CharField(max_length=20)
    imatge = models.CharField(max_length=200)
    sol_a = models.CharField(max_length=60, blank=True, null=True)
    sol_b = models.CharField(max_length=60, blank=True, null=True)
    sol_c = models.CharField(max_length=60, blank=True, null=True)
    sol_d = models.CharField(max_length=60, blank=True, null=True)
    sol_e = models.CharField(max_length=60, blank=True, null=True)
    category = models.ForeignKey(Category, null=True, on_delete=models.PROTECT)

temes/views.py
from django.shortcuts import render
from temes.models import Category, Exercici


# Create your views here.

def temes(request):
    categories = Category.objects.all()
    return render(request, 'temes/temes.html', {"categories": categories})


def exercicis(request, id):
    exercicis = Exercici.objects.all().filter(category_id=id)
    return render(request, 'temes/exercicis.html', {"exercicis": exercicis})


def show_exercici(request, pk):
    show_exercici = Exercici.objects.get(pk=pk)
    return render(request, 'temes/exercici_gran.html',
                  {"show_exercici": show_exercici})

temes/templates/temes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>2nBAT</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link href="static/temes/css/style.css" rel="stylesheet">


</head>
<header>

    <nav id="navbar-1" class="navbar navbar-expand-lg navbar-light bg-light">

        <div class="container">
            <a class="navbar-brand" href="#">TECNO 2nBAT</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                                <ion-icon name="grid-outline"></ion-icon>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'temes:temes' %}">Temes</a>
                        </li>

                        </ul>
                </ul>
            </div>
        </div>
    </nav>

</header>

<body>

<div class="container">


{% block content %}

{%endblock%}
</div>
</body>
</html>

temes/templates/temes/exercici_gran.html
{% extends 'temes/base.html' %}
{% load static %}

{% block content %}

<div class="row ">
    <div class="col-sm ">
    </div>
    <div class="col-sm ">
        <h5>{{show_exercici.any}}</h5>
        <div class="mr-auto p-1">
            <img src="{% static show_exercici.imatge %}" alt="My image" width="700px">
        </div>
        <div class="mb-auto p-2">
            <a href="{% url 'temes:exercicis' show_exercici.category_id %}"
               class="btn btn-primary">
                Tornar
            </a>
        </div>


    </div>
    <div class="col-sm ">
    </div>

</div>

{%endblock%}

temes/templates/temes/exercicis.html
{% extends 'temes/base.html' %}
{% load static %}



{% block content %}
<div class="row ">

    <div class="col-sm ">
    </div>
    <div class="col-sm ">
        {% for i in exercicis reversed %}
        <div class="mb-auto p-2">
            <h5>{{i.any}}</h5>
        </div>
        <div class="mb-auto p-2">
            <img src="{% static i.imatge %}" alt="My image" width="600px">
        </div>
        <div class="mb-auto p-2">
            <a href="{% url 'temes:show' i.pk  %}"
               class="btn btn-primary">
                Exercici {{i.exercici}}
            </a>
        </div>
        <div class="card mb-4 shadow-sm">
        </div>
        {% endfor %}
    </div>
    <div class="col-sm ">
    </div>
</div>
{%endblock%}

temes/templates/temes/temes.html
{% extends 'temes/base.html' %}
{% load static %}
{% block content %}

{% for category in categories  %}
{% if forloop.first %}
<div class="row row-cols-1 row-cols-md-3 mb-3 text-center">{%endif%}
    <div class="col">
        <div class="card mb-4 shadow-sm">
            <div class="card-body">
                <a href="{% url 'temes:exercicis' category.id %}"
                   class="w-100 btn btn-lg btn-primary">
                    {{category.title}}
                </a>
                <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group mt-2">
                  <a href={{category.link_teoria}} type="button" class="btn btn-sm btn-outline-secondary">Teoria</a>
                </div>
              </div>
            </div>
        </div>
    </div>
    {% if forloop.counter|divisibleby:3 %}</div><div class="row row-cols-1 row-cols-md-3 mb-3 text-center">{%endif%}
    {% endfor %}
{%endblock%}